# Generated by Django 3.2.3 on 2021-05-20 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['productname']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['companyname']},
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.supplier'),
            preserve_default=False,
        ),
    ]
